### PR TITLE
feat: add files for iOS/macOS builds

### PR DESCRIPTION
**Pull request by SputNikPlop**
This lets the application be built on the iOS and macOS platforms.

### CODE REVIEW

**Comment by MateusRodCosta** [comment]
@SputNikPlop I believe your changes don't look much different than what already was on the ios branch (it seems that you did your changes without knowing there was a separate ios branch too).
But, does it have any meaningful changes that are worth merging right now? Also, maybe it would have been better to rebase on top of this repo's ios branch rather than merging it.

**Comment by SputNikPlop** [comment]
@MateusRodCosta I do think a rebase on top of the iOS branch would be better since I missed that you had an ios branch. I haven't ever done a rebase before so I can attempt that or just push another commit so you can merge it with your ios branch.

**Comment by MateusRodCosta** [comment]
@SputNikPlop IMHO, it's your choice whether you plan on rebasicng your current work on top of the repo's branch versus starting over based on the repo's branch.

I would personally recommend you to learn how to rewrite history with git as soon as possible (assuming you're a git beginner), while it might not be important right now, there are some repos that you might end up trying to contribute which might require rebasing on pull requests instead of using normal meger.
So, learning it now might be beneficial to you.

**Comment by MateusRodCosta** [comment]
Initial iOS support has been added in 1.2.0 via #10, therefore closing this PR.

**Pull request closed without merging**
